# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:bookstore
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Habilita o GraphiQL (interface visual para testar)
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.inspection.enabled=true
spring.graphql.exception.resolve-to-single-error=true'